kind: Cluster
metadata:
  name: mvsphani-tf-1
  project: defaultproject
spec:
  blueprint: default
  blueprintversion: Latest
  cloudprovider: phani-eks
  cniprovider: aws-cni
  type: eks
---
addons:
- name: aws-ebs-csi-driver
  version: latest
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mvsphani-tf-1
  region: us-west-2
  tags:
    email: mvsphani@rafay.co
    env: dev
  version: "1.26"
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  disableIMDSv1: false
  disablePodIMDS: false
  ebsOptimized: false
  efaEnabled: false
  enableDetailedMonitoring: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: true
      xRay: false
  instanceType: t3.small
  maxPodsPerNode: 50
  maxSize: 2
  minSize: 1
  name: ng-1
  privateNetworking: true
  version: "1.26"
  volumeEncrypted: false
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  disableIMDSv1: false
  disablePodIMDS: false
  ebsOptimized: false
  efaEnabled: false
  enableDetailedMonitoring: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: true
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: true
      xRay: false
  instanceType: t3.large
  maxPodsPerNode: 50
  maxSize: 2
  minSize: 1
  name: ng-2
  privateNetworking: true
  version: "1.26"
  volumeEncrypted: false
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
